package org.example.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2023-10-25T15:05:55.675+03:30
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "HumanSoapImpService",
                  wsdlLocation = "http://localhost:8080/api?wsdl",
                  targetNamespace = "http://soap.com/")
public class HumanSoapImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.com/", "HumanSoapImpService");
    public final static QName HumanSoapImpPort = new QName("http://soap.com/", "HumanSoapImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/api?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HumanSoapImpService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/api?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HumanSoapImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HumanSoapImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HumanSoapImpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public HumanSoapImpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HumanSoapImpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HumanSoapImpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns HumanSoap
     */
    @WebEndpoint(name = "HumanSoapImpPort")
    public HumanSoap getHumanSoapImpPort() {
        return super.getPort(HumanSoapImpPort, HumanSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HumanSoap
     */
    @WebEndpoint(name = "HumanSoapImpPort")
    public HumanSoap getHumanSoapImpPort(WebServiceFeature... features) {
        return super.getPort(HumanSoapImpPort, HumanSoap.class, features);
    }

}
